using MaxMind.Db.SourceGenerators.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace MaxMind.Db.SourceGenerators
{
    /// <summary>
    /// Debug version of enhanced generator to identify issues.
    /// Debug complete - enhanced generator fixed. This class can be removed.
    /// </summary>
    // [Generator] - Debug complete, enhanced generator fixed
    internal class DebugEnhancedGenerator : IIncrementalGenerator
    {
        private const string ConstructorAttributeFullName = "MaxMind.Db.ConstructorAttribute";

        /// <summary>
        /// Initialize the debug enhanced generator.
        /// </summary>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Add debug output to see if generator is running
            context.RegisterPostInitializationOutput(static ctx =>
            {
                var debugSource = @"// <auto-generated/>
// Debug Enhanced Generator - Starting initialization

namespace MaxMind.Db.Generated
{
    internal static class DebugInfo
    {
        public static string Status => ""Enhanced generator initialized"";
    }
}";
                ctx.AddSource("DebugEnhancedInit.g.cs", SourceText.From(debugSource, Encoding.UTF8));
            });

            // Use simple syntax provider to check for classes
            var classNodes = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (context, _) => (Class: (ClassDeclarationSyntax)context.Node, context.SemanticModel))
                .WithTrackingName("ClassNodes");

            // Collect all classes and generate debug info
            context.RegisterSourceOutput(classNodes.Collect(), GenerateDebugInfo);

            // Try ForAttributeWithMetadataName approach - look for constructor methods with the attribute
            var attributeNodes = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    ConstructorAttributeFullName,
                    predicate: static (node, _) => node is ConstructorDeclarationSyntax,
                    transform: static (context, _) =>
                    {
                        var constructor = (ConstructorDeclarationSyntax)context.TargetNode;
                        var containingClass = constructor.Parent as ClassDeclarationSyntax;
                        return (Class: containingClass, context.SemanticModel);
                    })
                .Where(static x => x.Class != null)
                .WithTrackingName("AttributeNodes");

            context.RegisterSourceOutput(attributeNodes.Collect(), GenerateAttributeInfo);
        }

        private static void GenerateDebugInfo(SourceProductionContext context, ImmutableArray<(ClassDeclarationSyntax Class, SemanticModel SemanticModel)> classes)
        {
            var debugInfo = new StringBuilder();
            debugInfo.AppendLine("// <auto-generated/>");
            debugInfo.AppendLine($"// Debug Enhanced Generator - Found {classes.Length} classes");
            debugInfo.AppendLine();

            var constructorClasses = new List<string>();

            foreach (var (classDecl, semanticModel) in classes)
            {
                var typeSymbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                if (typeSymbol == null) continue;

                // Check if class has Constructor attribute
                var hasConstructorAttr = typeSymbol.Constructors
                    .Any(ctor => ctor.GetAttributes()
                        .Any(attr => attr.AttributeClass?.Name == "ConstructorAttribute" &&
                                   attr.AttributeClass?.ContainingNamespace?.ToDisplayString() == "MaxMind.Db"));

                if (hasConstructorAttr)
                {
                    constructorClasses.Add(typeSymbol.ToDisplayString());
                }

                debugInfo.AppendLine($"// Class: {typeSymbol?.ToDisplayString()} - HasConstructorAttr: {hasConstructorAttr}");
            }

            debugInfo.AppendLine();
            debugInfo.AppendLine("namespace MaxMind.Db.Generated");
            debugInfo.AppendLine("{");
            debugInfo.AppendLine("    internal static class ClassDebugInfo");
            debugInfo.AppendLine("    {");
            debugInfo.AppendLine($"        public static int TotalClasses => {classes.Length};");
            debugInfo.AppendLine($"        public static int ConstructorClasses => {constructorClasses.Count};");
            debugInfo.AppendLine("        public static string[] ConstructorClassNames => new string[]");
            debugInfo.AppendLine("        {");
            foreach (var className in constructorClasses)
            {
                debugInfo.AppendLine($"            \"{className}\",");
            }
            debugInfo.AppendLine("        };");
            debugInfo.AppendLine("    }");
            debugInfo.AppendLine("}");

            context.AddSource("ClassDebugInfo.g.cs", SourceText.From(debugInfo.ToString(), Encoding.UTF8));
        }

        private static void GenerateAttributeInfo(SourceProductionContext context, ImmutableArray<(ClassDeclarationSyntax? Class, SemanticModel SemanticModel)> attributeClasses)
        {
            var debugInfo = new StringBuilder();
            debugInfo.AppendLine("// <auto-generated/>");
            debugInfo.AppendLine($"// Debug Enhanced Generator - ForAttributeWithMetadataName found {attributeClasses.Length} classes");
            debugInfo.AppendLine();

            debugInfo.AppendLine("namespace MaxMind.Db.Generated");
            debugInfo.AppendLine("{");
            debugInfo.AppendLine("    internal static class AttributeDebugInfo");
            debugInfo.AppendLine("    {");
            debugInfo.AppendLine($"        public static int AttributeClasses => {attributeClasses.Length};");
            debugInfo.AppendLine("        public static string[] AttributeClassNames => new string[]");
            debugInfo.AppendLine("        {");
            foreach (var (classDecl, semanticModel) in attributeClasses)
            {
                if (classDecl != null)
                {
                    var typeSymbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                    if (typeSymbol != null)
                    {
                        debugInfo.AppendLine($"            \"{typeSymbol.ToDisplayString()}\",");
                    }
                }
            }
            debugInfo.AppendLine("        };");
            debugInfo.AppendLine("    }");

            // If we found classes, try to generate a simple TypeActivatorRegistration
            if (attributeClasses.Length > 0)
            {
                debugInfo.AppendLine();
                debugInfo.AppendLine("    internal static class TypeActivatorRegistration");
                debugInfo.AppendLine("    {");
                debugInfo.AppendLine("        public static void EnsureRegistered()");
                debugInfo.AppendLine("        {");
                debugInfo.AppendLine("            // Enhanced generator found classes but registration not implemented yet");
                debugInfo.AppendLine("        }");
                debugInfo.AppendLine("    }");
            }

            debugInfo.AppendLine("}");

            context.AddSource("AttributeDebugInfo.g.cs", SourceText.From(debugInfo.ToString(), Encoding.UTF8));
        }
    }
}