using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace MaxMind.Db.SourceGenerators
{
    /// <summary>
    /// Debug generator to test source generation functionality.
    /// Debug complete - enhanced generator fixed. This class can be removed.
    /// </summary>
    // [Generator] - Disabled, debug complete
    internal class DebugGenerator : ISourceGenerator
    {
        /// <summary>
        /// Initialize the debug generator.
        /// </summary>
        public void Initialize(GeneratorInitializationContext context)
        {
            // No initialization needed
        }

        /// <summary>
        /// Execute the debug generator.
        /// </summary>
        public void Execute(GeneratorExecutionContext context)
        {
            var source = @"// <auto-generated/>
// Debug generator test - this should appear if source generation is working

namespace MaxMind.Db.Generated
{
    internal static class TypeActivatorRegistration
    {
        public static void EnsureRegistered()
        {
            // Debug generator - no actual registrations
        }
    }
}";
            context.AddSource("TypeActivatorRegistration.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }
}