using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace MaxMind.Db.SourceGenerators
{
    /// <summary>
    /// Simple test version of enhanced generator to debug issues.
    /// </summary>
    // [Generator] - Temporarily disabled for debugging
    public class SimpleEnhancedGenerator : IIncrementalGenerator
    {
        /// <summary>
        /// Initialize the simple enhanced generator for debugging.
        /// </summary>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Generate a simple test file to ensure generator is running
            context.RegisterPostInitializationOutput(static ctx =>
            {
                var source = @"// <auto-generated/>
// Simple enhanced generator test file

namespace MaxMind.Db.Generated
{
    internal static class SimpleEnhancedTest
    {
        public static void Test() { }
    }
}";
                ctx.AddSource("SimpleEnhancedTest.g.cs", SourceText.From(source, Encoding.UTF8));
            });
        }
    }
}