using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace MaxMind.Db.SourceGenerators
{
    /// <summary>
    /// Source generator for creating AOT-compatible type activators for MaxMind.Db
    /// </summary>
    [Generator]
    public class TypeActivatorGenerator : IIncrementalGenerator
    {
        private const string ConstructorAttributeName = "MaxMind.Db.ConstructorAttribute";
        private const string ParameterAttributeName = "MaxMind.Db.ParameterAttribute";

        /// <summary>
        /// Initialize the incremental generator with modern cross-assembly support
        /// </summary>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Since Constructor attribute is applied to methods, not classes, we need to find 
            // all classes and check if they have constructors with the Constructor attribute
            var constructorTypes = context.SyntaxProvider
                .CreateSyntaxProvider(
                    (node, _) => node is ClassDeclarationSyntax,
                    (context, _) => GetTypeInfoFromClass(context))
                .Where(typeInfo => typeInfo != null)
                .Collect();

            // Register the output generation
            context.RegisterSourceOutput(constructorTypes, (context, types) => GenerateSource(context, types));
        }

        private TypeToGenerate? GetTypeInfoFromClass(GeneratorSyntaxContext context)
        {
            // Check if this class has any constructors with the Constructor attribute
            var classDecl = (ClassDeclarationSyntax)context.Node;
            var typeSymbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            
            if (typeSymbol == null) return null;
            
            // Skip abstract classes - they cannot be instantiated
            if (typeSymbol.IsAbstract) return null;
            
            // Allow public and internal types - private nested types can be accessed from same namespace
            if (typeSymbol.DeclaredAccessibility == Accessibility.Private) return null;

            // Find the constructor with the Constructor attribute
            var constructorWithAttr = typeSymbol.Constructors
                .FirstOrDefault(ctor => ctor.GetAttributes()
                    .Any(attr => IsConstructorAttributeByName(attr)));

            if (constructorWithAttr == null) return null;

            return CreateTypeInfo(typeSymbol, constructorWithAttr);
        }

        private void GenerateSource(SourceProductionContext context, ImmutableArray<TypeToGenerate?> types)
        {
            try
            {
                var validTypes = types.Where(t => t != null).Cast<TypeToGenerate>().ToList();
                
                // Group types by namespace to generate code in the same namespace as the types
                var typesByNamespace = validTypes.GroupBy(t => t.Namespace).ToList();
                
                // Generate activators in each namespace (allows access to private types)
                foreach (var namespaceGroup in typesByNamespace)
                {
                    GenerateActivatorsForNamespace(context, namespaceGroup.Key, namespaceGroup.ToList());
                }
                
                // Also generate a coordinator in MaxMind.Db.Generated that calls all the others
                GenerateCoordinatorClass(context, typesByNamespace.Select(g => g.Key).ToList());
            }
            catch (Exception ex)
            {
                // Generate a file with error information for debugging
                var errorCode = @"// <auto-generated/>
// Source generator error: " + ex.Message + @"
// Stack trace: " + ex.StackTrace?.Replace("\n", "\n// ") + @"

namespace MaxMind.Db.Generated
{
    internal static class TypeActivatorRegistration
    {
        public static void EnsureRegistered() { }
    }
}";
                context.AddSource("MaxMind.Db.Generated.TypeActivatorRegistration.g.cs", SourceText.From(errorCode, Encoding.UTF8));
            }
        }

        private void GenerateActivatorsForNamespace(SourceProductionContext context, string namespaceName, List<TypeToGenerate> types)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated at: " + DateTime.UtcNow.ToString("O"));
            sb.AppendLine($"// Found {types.Count} types with [Constructor] attribute in namespace '{namespaceName}'");
            foreach (var type in types)
            {
                sb.AppendLine($"//   {type.FullTypeName}");
            }
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using global::System;");
            sb.AppendLine("using global::MaxMind.Db;");
            sb.AppendLine();
            
            // Handle global namespace by putting it in a special namespace
            bool isGlobalNamespace = string.IsNullOrEmpty(namespaceName) || namespaceName == "<global namespace>";
            string actualNamespace = isGlobalNamespace ? "MaxMind.Db.Generated.Global" : namespaceName;
            sb.AppendLine($"namespace {actualNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Auto-registers source-generated activators for MaxMind.Db types");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    internal static class TypeActivatorRegistration");
            sb.AppendLine("    {");

            if (types.Count == 0)
            {
                sb.AppendLine("        // No types with [Constructor] attribute found - nothing to register");
            }
            else
            {
                // Generate a static constructor that registers all activators
                sb.AppendLine("        static TypeActivatorRegistration()");
                sb.AppendLine("        {");
                sb.AppendLine("#if NET8_0_OR_GREATER");
                
                foreach (var type in types)
                {
                    sb.AppendLine($"        // Register optimized activator for {type.FullTypeName}");
                    sb.AppendLine($"        {{");
                    
                    // Generate optimized activator with minimal overhead
                    sb.AppendLine($"            global::System.Func<object?[], object> activator = args => new {type.FullTypeName}(");
                    
                    for (int i = 0; i < type.Parameters.Count; i++)
                    {
                        var param = type.Parameters[i];
                        string cast = $"({param.Type})args[{i}]!";
                        
                        if (i < type.Parameters.Count - 1)
                            sb.AppendLine($"                {cast},");
                        else
                            sb.AppendLine($"                {cast}");
                    }
                    
                    sb.AppendLine("            );");
                    sb.AppendLine();
                    
                    // Generate pre-computed parameter mappings using compile-time constants
                    sb.AppendLine($"            var parameterMappings = new global::System.Collections.Generic.Dictionary<string, (int Position, global::System.Type ParameterType)>");
                    sb.AppendLine($"            {{");
                    
                    foreach (var param in type.Parameters)
                    {
                        var dbName = param.ParameterName ?? param.Name;
                        // Strip nullable syntax for typeof() - typeof(int?) is invalid, but typeof(int) works
                        var typeForTypeof = param.Type.EndsWith("?") ? param.Type.Substring(0, param.Type.Length - 1) : param.Type;
                        sb.AppendLine($"                {{ \"{dbName}\", ({param.Position}, typeof({typeForTypeof})) }},");
                    }
                    
                    sb.AppendLine($"            }};");
                    sb.AppendLine();
                    
                    // Generate empty collections (will be optimized for this specific type)
                    sb.AppendLine($"            var injectableMappings = new global::System.Collections.Generic.Dictionary<string, int>();");
                    sb.AppendLine();
                    
                    // Generate parameter position arrays for fast access (empty for now - would need additional attributes to populate)
                    sb.AppendLine($"            var networkParameterPositions = new int[] {{  }};");
                    sb.AppendLine($"            var alwaysCreatedParameterPositions = new int[] {{  }};");
                    sb.AppendLine();
                    
                    // Register with complete activator (this method must exist based on generated output)
                    sb.AppendLine($"            global::MaxMind.Db.SourceGeneratorSupport.RegisterCompleteActivator(");
                    sb.AppendLine($"                typeof({type.FullTypeName}),");
                    sb.AppendLine($"                activator,");
                    sb.AppendLine($"                parameterMappings,");
                    sb.AppendLine($"                injectableMappings,");
                    sb.AppendLine($"                networkParameterPositions,");
                    sb.AppendLine($"                alwaysCreatedParameterPositions);");
                    sb.AppendLine($"        }}");
                    sb.AppendLine();
                }

                sb.AppendLine("#endif");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            // Always generate the EnsureRegistered method
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Ensures that all type activators are registered. This method is called automatically.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static void EnsureRegistered()");
            sb.AppendLine("        {");
            sb.AppendLine("            // Static constructor will run when this method is called");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            // Create a safe filename from the namespace  
            var safeNamespace = isGlobalNamespace ? "Global" : namespaceName.Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace(" ", "_");
            context.AddSource($"TypeActivatorRegistration_{safeNamespace}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private void GenerateCoordinatorClass(SourceProductionContext context, List<string> namespaces)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated at: " + DateTime.UtcNow.ToString("O"));
            sb.AppendLine($"// Coordinator for {namespaces.Count} namespaces");
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using global::System;");
            sb.AppendLine();
            sb.AppendLine("namespace MaxMind.Db.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Auto-registers source-generated activators for MaxMind.Db types");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    internal static class TypeActivatorRegistration");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Ensures that all type activators are registered. This method is called automatically.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static void EnsureRegistered()");
            sb.AppendLine("        {");
            
            // Call EnsureRegistered on all namespace-specific classes
            foreach (var ns in namespaces)
            {
                bool isGlobalNs = string.IsNullOrEmpty(ns) || ns == "<global namespace>";
                string targetNamespace = isGlobalNs ? "MaxMind.Db.Generated.Global" : ns;
                sb.AppendLine($"            global::{targetNamespace}.TypeActivatorRegistration.EnsureRegistered();");
            }
            
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("MaxMind.Db.Generated.TypeActivatorRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private TypeToGenerate? CreateTypeInfo(INamedTypeSymbol typeSymbol, IMethodSymbol constructor)
        {
            var parameters = new List<ParameterInfo>();
            
            foreach (var param in constructor.Parameters)
            {
                var paramInfo = new ParameterInfo
                {
                    Name = param.Name,
                    Type = param.Type.ToDisplayString(),
                    Position = param.Ordinal
                };

                // Check for Parameter attribute to get the actual parameter name
                var paramAttr = param.GetAttributes()
                    .FirstOrDefault(a => IsParameterAttributeByName(a));
                if (paramAttr != null && paramAttr.ConstructorArguments.Length > 0)
                {
                    paramInfo.ParameterName = paramAttr.ConstructorArguments[0].Value?.ToString();
                }

                parameters.Add(paramInfo);
            }

            return new TypeToGenerate
            {
                TypeName = typeSymbol.Name,
                FullTypeName = typeSymbol.ToDisplayString(),
                Namespace = typeSymbol.ContainingNamespace.ToDisplayString(),
                Parameters = parameters
            };
        }

        private class TypeToGenerate
        {
            public string TypeName { get; set; } = "";
            public string FullTypeName { get; set; } = "";
            public string Namespace { get; set; } = "";
            public List<ParameterInfo> Parameters { get; set; } = new();
        }

        private class ParameterInfo
        {
            public string Name { get; set; } = "";
            public string Type { get; set; } = "";
            public int Position { get; set; }
            public string? ParameterName { get; set; }
        }


        private bool IsConstructorAttributeByName(AttributeData attr)
        {
            return attr.AttributeClass?.Name == "ConstructorAttribute" &&
                   attr.AttributeClass?.ContainingNamespace?.ToDisplayString() == "MaxMind.Db";
        }
        
        private bool IsParameterAttributeByName(AttributeData attr)
        {
            return attr.AttributeClass?.Name == "ParameterAttribute" &&
                   attr.AttributeClass?.ContainingNamespace?.ToDisplayString() == "MaxMind.Db";
        }


    }
}