using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MaxMind.Db.SourceGenerators
{
    /// <summary>
    /// Source generator for creating AOT-compatible type activators for MaxMind.Db
    /// </summary>
    [Generator]
    public class TypeActivatorGenerator : ISourceGenerator
    {
        private const string ConstructorAttributeName = "MaxMind.Db.ConstructorAttribute";
        private const string ParameterAttributeName = "MaxMind.Db.ParameterAttribute";

        /// <summary>
        /// Initialize the generator
        /// </summary>
        public void Initialize(GeneratorInitializationContext context)
        {
            // No initialization needed
        }

        /// <summary>
        /// Execute the generation
        /// </summary>
        public void Execute(GeneratorExecutionContext context)
        {
            try
            {
                var compilation = context.Compilation;
                var constructorAttribute = compilation.GetTypeByMetadataName(ConstructorAttributeName);
                
                if (constructorAttribute == null)
                {
                    // Generate empty activators if attribute not found
                    GenerateEmptyActivators(context);
                    return;
                }

                var typesToGenerate = new List<TypeToGenerate>();

                // Find all types in the current compilation that have [Constructor] attribute
                foreach (var syntaxTree in compilation.SyntaxTrees)
                {
                    var semanticModel = compilation.GetSemanticModel(syntaxTree);
                    var root = syntaxTree.GetRoot();
                    
                    var classes = root.DescendantNodes().OfType<ClassDeclarationSyntax>();
                    
                    foreach (var classDecl in classes)
                    {
                        var typeSymbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                        if (typeSymbol == null) continue;

                        // Check if this type has a constructor with [Constructor] attribute
                        foreach (var constructor in typeSymbol.Constructors)
                        {
                            var hasConstructorAttr = constructor.GetAttributes()
                                .Any(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, constructorAttribute));
                            
                            if (hasConstructorAttr)
                            {
                                var typeInfo = CreateTypeInfo(typeSymbol, constructor, compilation);
                                if (typeInfo != null)
                                {
                                    typesToGenerate.Add(typeInfo);
                                }
                                break; // Only one constructor per type
                            }
                        }
                    }
                }

                GenerateActivators(context, typesToGenerate);
            }
            catch (Exception ex)
            {
                // Generate a file with error information for debugging
                var errorCode = @"// <auto-generated/>
// Source generator error: " + ex.Message + @"
// Stack trace: " + ex.StackTrace?.Replace("\n", "\n// ") + @"

namespace MaxMind.Db.Generated
{
    internal static class TypeActivators
    {
        public static bool IsTypeSupported(System.Type type) => false;
        public static object CreateInstance(System.Type type, object?[] args) => 
            throw new System.NotSupportedException(""Source generator error: " + ex.Message + @""");
    }
}";
                context.AddSource("MaxMind.Db.Generated.TypeActivators.g.cs", SourceText.From(errorCode, Encoding.UTF8));
            }
        }

        private void GenerateEmptyActivators(GeneratorExecutionContext context)
        {
            var sourceCode = @"// <auto-generated/>
// Generated at: " + DateTime.UtcNow.ToString("O") + @"
// No types with [Constructor] attribute found

#nullable enable

using System;
using System.Collections.Generic;

namespace MaxMind.Db.Generated
{
    /// <summary>
    /// AOT-compatible type activators for MaxMind.Db types
    /// </summary>
    internal static class TypeActivators
    {        
        public static bool IsTypeSupported(Type type) => false;
        
        public static object CreateInstance(Type type, object?[] args) => 
            throw new NotSupportedException($""Type {type} is not registered for AOT activation"");
    }
}";
            context.AddSource("MaxMind.Db.Generated.TypeActivators.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }

        private void GenerateActivators(GeneratorExecutionContext context, List<TypeToGenerate> types)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated at: " + DateTime.UtcNow.ToString("O"));
            sb.AppendLine($"// Found {types.Count} types with [Constructor] attribute");
            foreach (var type in types)
            {
                sb.AppendLine($"//   {type.FullTypeName}");
            }
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using MaxMind.Db;");
            sb.AppendLine();
            sb.AppendLine("namespace MaxMind.Db.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Auto-registers source-generated activators for MaxMind.Db types");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    internal static class TypeActivatorRegistration");
            sb.AppendLine("    {");

            if (types.Count == 0)
            {
                sb.AppendLine("        // No types with [Constructor] attribute found - nothing to register");
            }
            else
            {
                // Generate a static constructor that registers all activators
                sb.AppendLine("        static TypeActivatorRegistration()");
                sb.AppendLine("        {");
                sb.AppendLine("#if NET8_0_OR_GREATER");
                
                foreach (var type in types)
                {
                    sb.AppendLine($"            // Register activator for {type.FullTypeName}");
                    sb.AppendLine($"            SourceGeneratorSupport.RegisterActivator(typeof({type.FullTypeName}), args => new {type.FullTypeName}(");
                    
                    for (int i = 0; i < type.Parameters.Count; i++)
                    {
                        var param = type.Parameters[i];
                        string cast = $"({param.Type})args[{i}]!";
                        
                        if (i < type.Parameters.Count - 1)
                            sb.AppendLine($"                {cast},");
                        else
                            sb.AppendLine($"                {cast}");
                    }
                    
                    sb.AppendLine("            ));");
                    sb.AppendLine();
                }

                sb.AppendLine("#endif");
                sb.AppendLine("        }");
                sb.AppendLine();

                // Generate a method to ensure the static constructor runs
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// Ensures that all type activators are registered. This method is called automatically.");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        public static void EnsureRegistered()");
                sb.AppendLine("        {");
                sb.AppendLine("            // Static constructor will run when this method is called");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("MaxMind.Db.Generated.TypeActivatorRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private TypeToGenerate? CreateTypeInfo(INamedTypeSymbol typeSymbol, IMethodSymbol constructor, Compilation compilation)
        {
            var parameters = new List<ParameterInfo>();
            
            foreach (var param in constructor.Parameters)
            {
                var paramInfo = new ParameterInfo
                {
                    Name = param.Name,
                    Type = param.Type.ToDisplayString(),
                    Position = param.Ordinal
                };

                // Check for Parameter attribute to get the actual parameter name
                var parameterAttribute = compilation.GetTypeByMetadataName(ParameterAttributeName);
                if (parameterAttribute != null)
                {
                    var paramAttr = param.GetAttributes()
                        .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, parameterAttribute));
                    if (paramAttr != null && paramAttr.ConstructorArguments.Length > 0)
                    {
                        paramInfo.ParameterName = paramAttr.ConstructorArguments[0].Value?.ToString();
                    }
                }

                parameters.Add(paramInfo);
            }

            return new TypeToGenerate
            {
                TypeName = typeSymbol.Name,
                FullTypeName = typeSymbol.ToDisplayString(),
                Namespace = typeSymbol.ContainingNamespace.ToDisplayString(),
                Parameters = parameters
            };
        }

        private class TypeToGenerate
        {
            public string TypeName { get; set; } = "";
            public string FullTypeName { get; set; } = "";
            public string Namespace { get; set; } = "";
            public List<ParameterInfo> Parameters { get; set; } = new();
        }

        private class ParameterInfo
        {
            public string Name { get; set; } = "";
            public string Type { get; set; } = "";
            public int Position { get; set; }
            public string? ParameterName { get; set; }
        }
    }
}